<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 40px; }
        h2 { text-align: center; color: #1e40af; margin-bottom: 10px; }
        .header { text-align: center; margin-bottom: 40px; }
        .info { margin: 10px 0; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 30px; }
        th, td { border: 1px solid #666; padding: 12px; text-align: left; font-size: 13px; }
        th { background-color: #f3f4f6; font-weight: bold; }
        .footer { margin-top: 60px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>
<div class="header">
    <h2>{{ $title }}</h2>
    <div class="info">
        <strong>Period:</strong> {{ \Carbon\Carbon::parse($from)->format('d M Y') }} — {{ \Carbon\Carbon::parse($to)->format('d M Y') }}
    </div>
    <div class="info">
        <strong>Generated on:</strong> {{ $generated_at }}
    </div>
</div>

<table>
    <thead>
    <tr>
        <th>#</th>
        <th>Employee Name</th>
        <th>Department</th>
        <th>Date</th>
        <th>Status</th>
        <th>Clock In</th>
        <th>Clock Out</th>
    </tr>
    </thead>
    <tbody>
    @forelse($records as $index => $record)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $record->employee->first_name }} {{ $record->employee->last_name }}</td>
            <td>{{ $record->employee->department->name ?? '-' }}</td>
            <td>{{ \Carbon\Carbon::parse($record->attendance_date)->format('d M Y') }}</td>
            <td>{{ strtoupper($record->status ?? 'absent') }}</td>
            <td>{{ $record->clock_in ? \Carbon\Carbon::parse($record->clock_in)->format('H:i') : '-' }}</td>
            <td>{{ $record->clock_out ? \Carbon\Carbon::parse($record->clock_out)->format('H:i') : '-' }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="7" class="text-center py-10 text-gray-500">No attendance records found for this period.</td>
        </tr>
    @endforelse
    </tbody>
</table>

<div class="footer">
    <p>Generated by HR System • {{ now()->format('d F Y, H:i') }}</p>
</div>
</body>
</html>
